### ISSUE TITLE
Feature idea tracking bug

### ISSUE THREAD

**Issue by taktoa** [chessai/rdss#1]
- [ ] Incremental connected components computation using union-find
- [ ] Dynamic dominator computation (using [this paper](https://arxiv.org/pdf/1604.02711.pdf))
- [ ] Dynamic postdominators (just flip the inserted edges)
- [ ] Branchless (SIMD?) union-find for C/C++
- [ ] Roaring bitmap?
- [ ] Path minima data structure (link-cut tree?)
- [ ] LRU or ARC cache
- [ ] Union-split-find map
- [ ] PQ tree
